### ISSUE TITLE
github上的模型是用的main中的默认参数训练的吗

### ISSUE THREAD

**Issue by soulbyfeng** [Sleepychord/ChinesePoemGeneration#1]
github上的模型是用的main中的默认参数训练的吗？
如果不是，可否透漏下主要参数，或者说如何调参来提高效果，万分感谢

**Comment by cenyk1230** [comment]
用默认参数是可以的，或者可以把hidden_size稍微改大一些比如512。你可以自己尝试一下看看怎样可以把loss训练得尽可能低。实际用的时候并不是生成的每一首诗都很好，需要挑选。

**Comment by soulbyfeng** [comment]
谢谢，指点
